const cityList = [
  'New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose',
  'London', 'Manchester', 'Birmingham', 'Leeds', 'Glasgow', 'Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice',
  'Tokyo', 'Yokohama', 'Osaka', 'Nagoya', 'Sapporo', 'Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon',
  'Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen', 'Chengdu', 'Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Ahmedabad',
  'Kolkata', 'Chennai', 'Surat', 'Pune', 'Jaipur', 'Lucknow', 'Kanpur', 'Nagpur', 'Indore', 'Thane',
  'Bhopal', 'Visakhapatnam', 'Patna', 'Vadodara','Bihar', 'Ghaziabad', 'Ludhiana', 'Agra', 'Nashik', 'Faridabad', 'Meerut',
  'Rajkot', 'Kalyan', 'Vasai-Virar', 'Varanasi', 'Srinagar', 'Aurangabad', 'Dhanbad', 'Amritsar', 'Navi Mumbai', 'Allahabad',
  'Ranchi', 'Howrah', 'Coimbatore', 'Jabalpur', 'Gwalior', 'Vijayawada', 'Jodhpur', 'Madurai', 'Raipur', 'Kota',
  'Guwahati', 'Chandigarh', 'Solapur', 'Hubballi', 'Tiruchirappalli', 'Bareilly', 'Moradabad', 'Mysore', 'Gurgaon', 'Aligarh',
  'Jalandhar', 'Bhubaneswar', 'Salem', 'Warangal', 'Guntur', 'Noida', 'Thiruvananthapuram', 'Bhiwandi', 'Saharanpur', 'Gorakhpur',
  'Bikaner', 'Amravati', 'Jamshedpur', 'Bhilai', 'Cuttack', 'Firozabad', 'Kochi', 'Nellore', 'Bhavnagar', 'Dehradun',
  'Durgapur', 'Asansol', 'Rourkela', 'Nanded', 'Kolhapur', 'Ajmer', 'Akola', 'Gulbarga', 'Jamnagar', 'Ujjain',
  'Loni', 'Siliguri', 'Jhansi', 'Ulhasnagar', 'Jammu', 'Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain', 'Ajman',
  'Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Ottawa',
  'Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'Rio de Janeiro', 'São Paulo', 'Brasília', 'Salvador', 'Fortaleza',
  'Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Rome', 'Milan', 'Naples', 'Turin', 'Palermo',
  'Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Kazan', 'Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Adana',
  'Cairo', 'Alexandria', 'Giza', 'Shubra El Kheima', 'Port Said', 'Lagos', 'Abuja', 'Kano', 'Ibadan', 'Benin City',
  'Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret', 'Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya', 'Khon Kaen',
  'Hanoi', 'Ho Chi Minh City', 'Da Nang', 'Hai Phong', 'Can Tho', 'Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Bekasi',
  'Manila', 'Quezon City', 'Davao City', 'Cebu City', 'Zamboanga City', 'Tehran', 'Mashhad', 'Isfahan', 'Karaj', 'Shiraz',
  'Baghdad', 'Basra', 'Mosul', 'Erbil', 'Kirkuk'
];
